# Generated by Django 6.0.6 on 2026-07-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите заголовок статьи блога",
                        max_length=200,
                        unique=True,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Введите содержимое статьи",
                        null=True,
                        verbose_name="Содержимое",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение (превью)",
                        null=True,
                        upload_to="images/",
                        verbose_name="Изображение (превью)",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликовано"),
                ),
                ("views_counter", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["name"],
            },
        ),
    ]
